import type { CharEntry, Reading } from '../data/types.js'
import { compareHits, type Hit, type Dictionary } from '../data/dictionary.js'
import { bandForLevel, matchesScriptFilter, type SearchFilters } from './search.js'
import { splitRegisterLabels } from './register.js'

export type Posting = {
  entry: CharEntry
  readingIndex: number
  glossIndex: number
  tier: 1 | 2 | 3
}

export type EnglishIndex = Map<string, Posting[]>

export type EnglishResult = Hit & {
  matchedGloss: string
  tier: 1 | 2 | 3
}

/**
 * Check if a raw gloss should be skipped (cross-reference or label).
 * Matches "variant of …", "old variant of …", "see …", "surname …", "CL:…".
 */
export function shouldSkipGloss(gloss: string): boolean {
  return /^(?:(?:[\w-]+ )*variant of\b|see\s+|surname\b|cl:)/i.test(gloss)
}

/**
 * Normalize a single gloss piece from CC-CEDICT:
 * 1. Lowercase
 * 2. Strip parenthetical labels like (literary), (bound form), (fig.)
 * 3. Skip glosses: variant of …, see …, surname …, CL:…
 * 4. Strip leading "to ", "a ", "the "
 * Returns null if skipped or empty.
 */
export function normalizeGloss(raw: string): string | null {
  let s = raw.toLowerCase()
  s = s.replace(/\([^)]*\)/g, ' ')
  s = s.replace(/\s+/g, ' ').trim()

  if (!s) return null
  if (shouldSkipGloss(s)) return null

  s = s.replace(/^(?:to|a|the)\s+/i, '').trim()
  return s || null
}

/**
 * Normalize a user query:
 * - Lowercase
 * - Strip parentheticals
 * - Strip leading "to ", "a ", "the "
 * - Trim and collapse multiple spaces
 */
export function normalizeQuery(query: string): string {
  let s = query.toLowerCase()
  s = s.replace(/\([^)]*\)/g, ' ')
  s = s.replace(/\s+/g, ' ').trim()
  s = s.replace(/^(?:to|a|the)\s+/i, '').trim()
  return s
}

/**
 * Tokenize a normalized gloss into individual word tokens.
 */
export function tokenizeGloss(normalized: string): string[] {
  return normalized
    .split(/\s+/)
    .map((w) => w.replace(/^[^\w]+|[^\w]+$/g, ''))
    .filter(Boolean)
}

/**
 * Extract all glosses for a reading, splitting on semicolons.
 * Returns array of { raw, normalized } with null normalized glosses filtered out.
 */
export function extractGlosses(reading: {
  meanings: string[]
}): { raw: string; normalized: string }[] {
  const glosses: { raw: string; normalized: string }[] = []
  for (const rawMeaning of reading.meanings) {
    for (const part of rawMeaning.split(';')) {
      const raw = part.trim()
      const normalized = normalizeGloss(raw)
      if (normalized !== null) {
        glosses.push({ raw, normalized })
      }
    }
  }
  return glosses
}

/**
 * Get the matched gloss for a reading and glossIndex, returning the raw text.
 */
export function getGloss(reading: Reading, glossIndex: number): string {
  const glosses = extractGlosses(reading)
  return glosses[glossIndex]?.raw ?? (reading.meanings[0] || '')
}

const registeredCache = new WeakMap<Posting, boolean>()

function isRegistered(posting: Posting): boolean {
  let reg = registeredCache.get(posting)
  if (reg === undefined) {
    const reading = posting.entry.readings[posting.readingIndex]
    const gloss = getGloss(reading, posting.glossIndex)
    const { labels } = splitRegisterLabels(gloss)
    reg = labels.some((l) => l !== 'fig')
    registeredCache.set(posting, reg)
  }
  return reg
}

/**
 * Compare two postings for ranking within an English index key.
 * 1. Tier ascending (Tier 1 < Tier 2 < Tier 3)
 * 2. Registered status: no register labels before register labels
 * 3. compareHits (frequency / strokes / char / tone)
 * 4. Earlier glosses before later glosses (glossIndex ascending as last tiebreak)
 */
export function comparePostings(a: Posting, b: Posting): number {
  if (a.tier !== b.tier) {
    return a.tier - b.tier
  }

  const aRegistered = isRegistered(a)
  const bRegistered = isRegistered(b)
  if (aRegistered !== bRegistered) {
    return aRegistered ? 1 : -1
  }

  const aHit: Hit = { entry: a.entry, reading: a.entry.readings[a.readingIndex] }
  const bHit: Hit = { entry: b.entry, reading: b.entry.readings[b.readingIndex] }
  const hitDiff = compareHits(aHit, bHit)
  if (hitDiff !== 0) {
    return hitDiff
  }
  return a.glossIndex - b.glossIndex
}

/**
 * Build the inverted index mapping English tokens/phrases to pre-sorted postings.
 */
export function buildEnglishIndex(dict: Dictionary): EnglishIndex {
  const tempIndex = new Map<string, Posting[]>()

  for (const entry of dict.byChar.values()) {
    for (let readingIndex = 0; readingIndex < entry.readings.length; readingIndex++) {
      const reading = entry.readings[readingIndex]
      const glosses = extractGlosses(reading)

      for (let glossIndex = 0; glossIndex < glosses.length; glossIndex++) {
        const { normalized } = glosses[glossIndex]
        const words = tokenizeGloss(normalized)
        const n = words.length
        if (n === 0) continue

        // Track best tier for each key generated by this gloss
        const bestTierForKey = new Map<string, 1 | 2 | 3>()

        function setTier(key: string, tier: 1 | 2 | 3): void {
          if (!key) return
          const existing = bestTierForKey.get(key)
          if (existing === undefined || tier < existing) {
            bestTierForKey.set(key, tier)
          }
        }

        // Tier 1: exact normalized gloss
        setTier(normalized, 1)
        const joinedWords = words.join(' ')
        if (joinedWords !== normalized) {
          setTier(joinedWords, 1)
        }

        // Tier 2: prefix phrases (gloss starts with query as a word boundary)
        for (let i = 1; i < n; i++) {
          const prefix = words.slice(0, i).join(' ')
          setTier(prefix, 2)
        }

        // Tier 3: sub-phrases anywhere else in gloss
        for (let i = 1; i < n; i++) {
          for (let j = i + 1; j <= n; j++) {
            const sub = words.slice(i, j).join(' ')
            setTier(sub, 3)
          }
        }

        // Add postings to temp index
        for (const [key, tier] of bestTierForKey.entries()) {
          let list = tempIndex.get(key)
          if (!list) {
            list = []
            tempIndex.set(key, list)
          }
          list.push({
            entry,
            readingIndex,
            glossIndex,
            tier,
          })
        }
      }
    }
  }

  // Pre-sort and deduplicate by character for each key
  const finalIndex: EnglishIndex = new Map()

  for (const [key, postings] of tempIndex.entries()) {
    postings.sort(comparePostings)

    const deduped: Posting[] = []
    const seenChars = new Set<string>()

    for (const posting of postings) {
      if (!seenChars.has(posting.entry.char)) {
        seenChars.add(posting.entry.char)
        deduped.push(posting)
      }
    }

    finalIndex.set(key, deduped)
  }

  return finalIndex
}

let cachedIndex: { dict: Dictionary; index: EnglishIndex } | null = null

/**
 * Get or lazily build and cache the English index for a dictionary.
 */
export function getOrBuildEnglishIndex(dict: Dictionary): EnglishIndex {
  if (cachedIndex && cachedIndex.dict === dict) {
    return cachedIndex.index
  }
  const index = buildEnglishIndex(dict)
  cachedIndex = { dict, index }
  return index
}

/**
 * Search the English index with query and filters.
 */
export function searchEnglish(
  index: EnglishIndex,
  query: string,
  filters: SearchFilters,
): EnglishResult[] {
  const normalized = normalizeQuery(query)
  if (!normalized) return []

  const postings = index.get(normalized) ?? []
  const results: EnglishResult[] = []
  const seenChars = new Set<string>()

  for (const posting of postings) {
    if (seenChars.has(posting.entry.char)) continue

    // Script filter
    if (!matchesScriptFilter(posting.entry.script, filters.script)) {
      continue
    }

    // Skip entries with no meanings and no strokes
    const reading = posting.entry.readings[posting.readingIndex]
    if (reading.meanings.length === 0 && !posting.entry.hasStrokes) {
      continue
    }

    // HSK filters
    if (filters.hskFilter) {
      if (posting.entry.hsk === null || posting.entry.hsk > filters.hskLevel) {
        continue
      }
      if (filters.handwritingOnly) {
        const requiredBand = bandForLevel(filters.hskLevel)
        if (posting.entry.hskWriteBand === null || posting.entry.hskWriteBand > requiredBand) {
          continue
        }
      }
    }

    seenChars.add(posting.entry.char)
    const matchedGloss = getGloss(reading, posting.glossIndex)
    results.push({
      entry: posting.entry,
      reading,
      matchedGloss,
      tier: posting.tier,
    })
  }

  return results
}
